runtime! debian.vim

let mapleader = "-"


" --- Custom Mappings ---
map Y y$
nnoremap <CR> o<ESC>


" --- UI ---
set number
set cmdheight=2
set ruler
set laststatus=2
set showcmd
set showmatch
set wildmenu
set lazyredraw

if has("autocmd")
  filetype plugin indent on
  " move cursor to where you left
  :au BufReadPost *
	 \ if line("'\"") > 1 && line("'\"") <= line("$") && &ft !~# 'commit'
	 \ |   exe "normal! g`\""
	 \ | endif
endif


" --- Search ---
set incsearch
set hlsearch


" --- Spaces, tabs and indentation ---
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set autoindent


" --- Folding ---
set foldenable
set foldlevelstart=15
set foldnestmax=10
set foldmethod=indent


" --- Colors and theme ---
if has("syntax")
  syntax on
endif

let g:gruvbox_bold = 1
let g:gruvbox_underline = 1
let g:gruvbox_italic = 1

set background=dark
colorscheme gruvbox
hi Normal guibg=NONE ctermbg=NONE


" --- Misc ---
set nomodeline
set nostartofline
set novisualbell
set history=200
